/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.73
 * Generated at: 2021-05-14 10:50:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class selectMember_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<!--\n");
      out.write("This is a starter template page. Use this page to start your new project from\n");
      out.write("scratch. This page gets rid of all links and provides the needed markup only.\n");
      out.write("-->\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<title>AdminLTE 3 | Starter</title>\n");
      out.write("\n");
      out.write("<!-- Google Font: Source Sans Pro -->\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback\">\n");
      out.write("<!-- Font Awesome Icons -->\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/resources/bootstrap/plugins/fontawesome-free/css/all.min.css\">\n");
      out.write("<!-- Theme style -->\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/resources/bootstrap/dist/css/adminlte.min.css\">\n");
      out.write("</head>\n");
      out.write("<body class=\"hold-transition sidebar-mini\">\n");
      out.write("\t<div class=\"wrapper\">\n");
      out.write("\n");
      out.write("\t\t<!-- Navbar -->\n");
      out.write("\t\t<nav\n");
      out.write("\t\t\tclass=\"main-header navbar navbar-expand navbar-white navbar-light\">\n");
      out.write("\t\t\t<!-- SEARCH FORM -->\n");
      out.write("\t\t\t<form class=\"form-inline ml-3\">\n");
      out.write("\t\t\t\t<div class=\"input-group input-group-sm\">\n");
      out.write("\t\t\t\t\t<input class=\"form-control form-control-navbar\" type=\"search\"\n");
      out.write("\t\t\t\t\t\tplaceholder=\"Search\" aria-label=\"Search\">\n");
      out.write("\t\t\t\t\t<div class=\"input-group-append\">\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-navbar\" type=\"submit\">\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fas fa-search\"></i>\n");
      out.write("\t\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</form>\n");
      out.write("\n");
      out.write("\t\t\t<!-- Right navbar links -->\n");
      out.write("\t\t\t<ul class=\"navbar-nav ml-auto\">\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\n");
      out.write("\t\t\t\t\tdata-widget=\"fullscreen\" href=\"#\" role=\"button\"> <i\n");
      out.write("\t\t\t\t\t\tclass=\"fas fa-expand-arrows-alt\"></i>\n");
      out.write("\t\t\t\t</a></li>\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\n");
      out.write("\t\t\t\t\tdata-widget=\"control-sidebar\" data-slide=\"true\" href=\"#\"\n");
      out.write("\t\t\t\t\trole=\"button\"> <i class=\"fas fa-th-large\"></i>\n");
      out.write("\t\t\t\t</a></li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t</nav>\n");
      out.write("\t\t<!-- /.navbar -->\n");
      out.write("\n");
      out.write("\t\t<!-- Main Sidebar Container -->\n");
      out.write("\t\t<aside class=\"main-sidebar sidebar-dark-primary elevation-4\">\n");
      out.write("\t\t\t<!-- Brand Logo -->\n");
      out.write("\t\t\t<a href=\"index3.html\" class=\"brand-link\"> <img\n");
      out.write("\t\t\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/resources/bootstrap/dist/img/AdminLTELogo.png\"\n");
      out.write("\t\t\t\talt=\"AdminLTE Logo\" class=\"brand-image img-circle elevation-3\"\n");
      out.write("\t\t\t\tstyle=\"opacity: .8\"> <span\n");
      out.write("\t\t\t\tclass=\"brand-text font-weight-light\">AdminLTE 3</span>\n");
      out.write("\t\t\t</a>\n");
      out.write("\t\t\t<!-- Sidebar -->\n");
      out.write("\t\t\t<div class=\"sidebar\">\n");
      out.write("\t\t\t\t<!-- Sidebar Menu -->\n");
      out.write("\t\t\t\t<nav class=\"mt-2\">\n");
      out.write("\t\t\t\t\t<ul class=\"nav nav-pills nav-sidebar flex-column\"\n");
      out.write("\t\t\t\t\t\tdata-widget=\"treeview\" role=\"menu\" data-accordion=\"false\">\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\"><a\n");
      out.write("\t\t\t\t\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("/select\"\n");
      out.write("\t\t\t\t\t\t\tclass=\"nav-link active\"> <i class=\"nav-icon fas fa-th\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t<p>Member Select</p>\n");
      out.write("\t\t\t\t\t\t</a></li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</nav>\n");
      out.write("\t\t\t\t<!-- /.sidebar-menu -->\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</aside>\n");
      out.write("\n");
      out.write("\t\t<!-- Content Wrapper. Contains page content -->\n");
      out.write("\t\t<div class=\"content-wrapper\">\n");
      out.write("\t\t\t<!-- Content Header (Page header) -->\n");
      out.write("\t\t\t<div class=\"content-header\">\n");
      out.write("\t\t\t\t<div class=\"container-fluid\">\n");
      out.write("\t\t\t\t\t<div class=\"row mb-2\">\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-6\">\n");
      out.write("\t\t\t\t\t\t\t<h1 class=\"m-0\">Member Select</h1>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<!-- /.col -->\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!-- /.row -->\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<!-- /.container-fluid -->\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- /.content-header -->\n");
      out.write("\n");
      out.write("\t\t\t<!-- Main content -->\n");
      out.write("\t\t\t<div class=\"content col-sm-12\">\n");
      out.write("\t\t\t\t<div class=\"container-fluid\">\n");
      out.write("\t\t\t\t\t<div class=\"card card-success\">\n");
      out.write("\t\t\t\t\t\t<div class=\"card-header\">\n");
      out.write("\t\t\t\t\t\t\t<h3 class=\"card-title\">Select Member</h3>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"card\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-body p-0\">\n");
      out.write("\t\t\t\t\t\t\t\t<table class=\"table\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<thead>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th style=\"width: 10px\">#</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th>ID</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th>Password</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th>Name</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th>Email</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th>Phone</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th>manage</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t</thead>\n");
      out.write("\t\t\t\t\t\t\t\t\t<tbody>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>2.</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>Clean database</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress progress-xs\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress-bar bg-warning\" style=\"width: 70%\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td><span class=\"badge bg-warning\">70%</span></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>3.</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>Cron job running</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress progress-xs progress-striped active\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress-bar bg-primary\" style=\"width: 30%\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td><span class=\"badge bg-primary\">30%</span></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>4.</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>Fix and squish bugs</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress progress-xs progress-striped active\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress-bar bg-success\" style=\"width: 90%\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td><span class=\"badge bg-success\">90%</span></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t</tbody>\n");
      out.write("\t\t\t\t\t\t\t\t</table>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<!-- /.card-body -->\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<!-- /.container-fluid -->\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- /.content -->\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- /.content-wrapper -->\n");
      out.write("\n");
      out.write("\t\t<!-- Main Footer -->\n");
      out.write("\t\t<footer class=\"main-footer\">\n");
      out.write("\t\t\t<!-- To the right -->\n");
      out.write("\t\t\t<div class=\"float-right d-none d-sm-inline\">Anything you want</div>\n");
      out.write("\t\t\t<!-- Default to the left -->\n");
      out.write("\t\t\t<strong>Copyright &copy; 2021-01 403 [yezin]</strong>\n");
      out.write("\t\t</footer>\n");
      out.write("\t</div>\n");
      out.write("\t<!-- ./wrapper -->\n");
      out.write("\n");
      out.write("\t<!-- REQUIRED SCRIPTS -->\n");
      out.write("\t<!-- Script -->\n");
      out.write("\t<script type=\"text/javascript\">\n");
      out.write("\t\t$\n");
      out.write("\t\t{\n");
      out.write("\t\t\tscript\n");
      out.write("\t\t}\n");
      out.write("\t</script>\n");
      out.write("\t<!-- jQuery -->\n");
      out.write("\t<script\n");
      out.write("\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/resources/bootstrap/plugins/jquery/jquery.min.js\"></script>\n");
      out.write("\t<!-- Bootstrap 4 -->\n");
      out.write("\t<script\n");
      out.write("\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/resources/bootstrap/plugins/bootstrap/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("\t<!-- AdminLTE App -->\n");
      out.write("\t<script\n");
      out.write("\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/resources/bootstrap/dist/js/adminlte.min.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /selectMember.jsp(121,10) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty memList }", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td colspan=\"4\">í´ë¹ë´ì© ë¸ì¡´ì¬</td>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    }
    return false;
  }
}
